version: '2'

services:
    php:
        build:
            context: ./docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${APP_PATH}:/var/www/app
    nginx:
        build: ./docker/nginx
        ports:
            - ${NGINX_EXTERNAL_WEB_PORT}:80
        volumes_from:
            - php
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx
